import type { Metadata } from "next";
import { ThemeToggle } from "../../ThemeToggle";

export const metadata: Metadata = { title: "S&E LAB â€” äººå£°ç§»é™¤ä¸ŽéŸ³é¢‘åˆ†ç¦»", description: "S&E LAB æ˜¯ DrunKitten æä¾›äººå£°ç§»é™¤ä¸Žä¼´å¥æå–çš„çº¿ä¸ŠéŸ³é¢‘æœåŠ¡ã€‚", icons: { icon: "/favicon-se-lab-v3.png?v=3", shortcut: "/favicon-se-lab-v3.png?v=3" } };
const Arrow = () => <span aria-hidden="true">â†—</span>;
function DrunKittenWordmark(){return <span className="themeWord wordDrunkitten seParentLogo" aria-hidden="true"><img className="logoLight" src="/drunkitten-word-black.png" alt=""/><img className="logoDark" src="/drunkitten-word-white.png" alt=""/></span>}
function SELabWordmark(){return <span className="themeWord wordSELab seFooterWord" aria-hidden="true"><img className="logoLight" src="/se-lab-word-black.png" alt=""/><img className="logoDark" src="/se-lab-word-white.png" alt=""/></span>}

export default function ChineseSELabPage(){return <main className="sePage" lang="zh-CN">
  <nav className="nav" aria-label="S&E LAB å¯¼èˆª"><a className="seNavBrand" href="/zh/se-lab" aria-label="S&E LAB é¦–é¡µ"><img src="/s-and-e-lab-mark.png" alt=""/><SELabWordmark/></a><div className="navLinks"><a href="/zh">DrunKitten</a><a href="/zh/production">éŸ³ä¹åˆ¶ä½œ</a><a href="https://darrenk.drunkitten.com/zh">Darren</a><ThemeToggle/><a className="languageSwitch" href="/se-lab" lang="en">EN</a></div></nav>

  <section className="seHero" id="top"><div className="seHeroGlow" aria-hidden="true"><i/><i/></div><div className="seHeroCopy"><p className="eyebrow"><span/> DrunKitten åˆ›æ„æœåŠ¡</p><h1>å¬è§æ›¾ç»<br/><em>éšè—å…¶ä¸­çš„å£°éŸ³ã€‚</em></h1><p>ä¸ºåˆ›ä½œè€…ã€ç»ƒä¹ ã€å‰ªè¾‘ä¸Žæ–°åˆ›æ„æä¾›äººå£°ç§»é™¤åŠä¼´å¥æå–æœåŠ¡ï¼Œè®©å£°éŸ³æ‹¥æœ‰æ›´å¤šç©ºé—´ã€‚</p><div className="heroActions"><a className="button primary" href="#services">æŽ¢ç´¢æœåŠ¡ <Arrow/></a><a className="button secondary" href="#process">è¿ä½œæ–¹å¼</a></div></div><div className="seHeroCard"><span className="seStatus"><i/> å®žéªŒå®¤åœ¨çº¿</span><img src="/s-and-e-lab-logo.png" alt="S&E LAB â€” å£°éŸ³ä¸Žç¼–è¾‘"/></div></section>

  <section className="seServices section" id="services"><div className="sectionIntro"><p className="kicker">01 Â· æœåŠ¡</p><h2>åˆ†ç¦»æ··éŸ³ã€‚<br/>ä¿ç•™æ— é™å¯èƒ½ã€‚</h2></div><div className="seServiceGrid"><article><span className="seServiceIcon">V</span><small>01</small><h3>ç§»é™¤äººå£°</h3><p>é™ä½Žæˆ–ç§»é™¤ä¸»è¦äººå£°ï¼Œåˆ¶ä½œé€‚åˆç»ƒä¹ ã€è¡¨æ¼”æˆ–å‰ªè¾‘ä½¿ç”¨çš„ä¼´å¥ç‰ˆæœ¬ã€‚</p><span className="seTag">ä¼´å¥è¾“å‡º</span></article><article><span className="seServiceIcon">M</span><small>02</small><h3>æå–ä¼´å¥</h3><p>å°†éŸ³ä¹ä¸Žäººå£°åˆ†å¼€ï¼Œè®©ä½ ä¸“æ³¨äºŽç¼–æ›²ã€ç ”ç©¶æ­Œæ›²æˆ–å‘å±•æ–°çš„åˆ›æ„ã€‚</p><span className="seTag">çº¯éŸ³ä¹è¾“å‡º</span></article><article className="seServiceNote"><span className="seServiceIcon">â†—</span><small>03</small><h3>çº¿ä¸Šäº¤ä»˜</h3><p>åœ¨çº¿æäº¤æ­Œæ›²å¹¶æŽ¥æ”¶åˆ†ç¦»ç»“æžœâ€”â€”ç®€å•ã€ä¸“æ³¨ï¼Œå¹¶é€‚åˆä¸ªäººé¡¹ç›®ã€‚</p><span className="seTag">çŽ°å·²å¼€æ”¾</span></article></div></section>

  <section className="seProcess section" id="process"><div className="seProcessCopy"><p className="kicker">02 Â· æµç¨‹</p><h2>ä»Žä¸€æ¡éŸ³è½¨<br/>èµ°å‘ä¸¤ä¸ªæ–°æ–¹å‘ã€‚</h2><p>S&amp;E LAB ä¼šå°†å®Œæˆçš„æ­Œæ›²åˆ†ç¦»æˆä¸»è¦äººå£°ä¸Žåº•å±‚éŸ³ä¹ã€‚</p></div><div className="seSteps"><article><span>1</span><div><h3>å‘é€æ­Œæ›²</h3><p>æä¾›ä½ å¸Œæœ›åˆ†ç¦»çš„éŸ³é¢‘ã€‚</p></div></article><article><span>2</span><div><h3>å®žéªŒå®¤è¿›è¡Œåˆ†ç¦»</h3><p>äººå£°ä¸ŽéŸ³ä¹å…ƒç´ ä¼šè¢«å¤„ç†æˆä¸åŒçš„è¾“å‡ºæ–‡ä»¶ã€‚</p></div></article><article><span>3</span><div><h3>æŽ¥æ”¶æ–‡ä»¶</h3><p>åœ¨çº¿å–å¾—ç»“æžœï¼Œä¸ºä¸‹ä¸€æ¬¡ä½¿ç”¨åšå¥½å‡†å¤‡ã€‚</p></div></article></div></section>

  <section className="seUseCases section"><p className="kicker">03 Â· é€‚åˆç”¨é€”</p><div className="seMarquee"><span>ç»ƒä¹ </span><i/><span>è¡¨æ¼”</span><i/><span>æ··éŸ³</span><i/><span>å‰ªè¾‘</span><i/><span>ç ”ç©¶</span></div></section>

  <section className="seAbout section" id="about-lab"><div className="seAboutLogo"><img src="/s-and-e-lab-mark.png" alt="S&E LAB"/></div><div><p className="kicker">04 Â· åˆ›æ„ä½“ç³»çš„ä¸€éƒ¨åˆ†</p><h2>è¯žç”ŸäºŽ DrunKittenã€‚</h2><p>S&amp;E LAB æ˜¯ DrunKitten ç›®å‰æ´»è·ƒçš„éŸ³é¢‘æœåŠ¡åˆ†æ”¯ï¼Œç”± Darren Khaw åˆ›ç«‹å¹¶è¿è¥ã€‚</p><a className="button secondary" href="/zh">è®¤è¯† DrunKitten <Arrow/></a></div></section>

  <footer className="seFooter"><div className="seFooterIdentity"><a className="seFooterBrand" href="/zh/se-lab" aria-label="S&E LAB é¦–é¡µ"><img src="/s-and-e-lab-mark.png" alt=""/><SELabWordmark/></a><a className="seFooterBy" href="/zh" aria-label="DrunKitten é¦–é¡µ"><span>by</span><DrunKittenWordmark/></a></div><div className="brandFooterCopy"><p>å£°éŸ³ä¸Žç¼–è¾‘å®žéªŒå®¤ Â· çº¿ä¸ŠéŸ³é¢‘æœåŠ¡</p><nav className="brandContactLinks" aria-label="è”ç³» S&E LAB"><a href="mailto:darrenkhaw@drunkitten.com">ç”µå­é‚®ä»¶</a><a href="https://discord.gg/QxKMNTXUke" target="_blank" rel="noreferrer">Discord â†—</a></nav></div><a href="#top">è¿”å›žé¡¶éƒ¨ â†‘</a><small>Â© {new Date().getFullYear()} Darren Khaw Â· ç‹¬ç«‹åˆ›æ„é¡¹ç›®</small></footer>
</main>}
