import type { Metadata } from "next";
import { ThemeToggle } from "../ThemeToggle";

export const metadata: Metadata = {
  title: "Darren Khaw â€” å­¦ç”Ÿä¸ªäººä½œå“é›†",
  description: "Darren Khaw çš„ä¸ªäººä½œå“é›†ï¼Œä¸€åæ¥è‡ªé©¬æ¥è¥¿äºšçš„ 18 å²å­¦ç”Ÿã€‚",
  icons: { icon: "/favicon-darren-v4.png?v=4", shortcut: "/favicon-darren-v4.png?v=4" },
};

function DarrenLogo({ className = "" }: { className?: string }) { return <span className={`themeWord wordDarren ${className}`} aria-hidden="true"><img className="logoLight" src="/darren-khaw-black.png" alt=""/><img className="logoDark" src="/darren-khaw-white.png" alt=""/></span>; }

export default function DarrenChinesePage(){return <main className="darrenPage" lang="zh-CN">
  <nav className="nav darrenStandaloneNav" aria-label="Darren Khaw å¯¼èˆª"><a className="darrenNavBrand" href="/zh" aria-label="Darren Khaw é¦–é¡µ"><DarrenLogo/></a><div className="navLinks"><ThemeToggle/><a className="languageSwitch" href="/" lang="en">EN</a></div></nav>

  <section className="darrenHero" id="top"><div className="darrenGrid" aria-hidden="true"/><div className="darrenHeroCopy"><p className="eyebrow"><span/> å­¦ç”Ÿ</p><DarrenLogo className="darrenHeroLogo"/><h1>å¯»æ‰¾è‡ªå·±çš„å£°éŸ³ã€‚<br/><em>ä¸€æ­¥ä¸€æ­¥ï¼Œèµ°ä¸Šæ¯ä¸ªèˆžå°ã€‚</em></h1><p>æˆ‘æ˜¯ Darren Khawï¼Œä¸€åæ¥è‡ªé©¬æ¥è¥¿äºšçš„ 18 å²å­¦ç”Ÿã€‚æˆ‘å‚åŠ æ­Œå”±æ¯”èµ›ï¼Œå¹¶åœ¨æ¯ä¸€æ¬¡è¡¨æ¼”ä¸­ç»§ç»­æˆé•¿ã€‚</p><div className="heroActions"><a className="button primary" href="#achievements">æŸ¥çœ‹æˆ‘çš„æˆå°± â†“</a></div></div><div className="darrenIdentityCard"><img className="identityPhoto" src="/darren-khaw-profile.png" alt="Darren Khaw åœ¨èˆžå°ä¸Šæ¼”å”±"/><h2>Darren Khaw</h2><div className="identityNames"><p><span>å…¨å</span>Khaw Zhen Xuan</p><p><span>ä¸­æ–‡å§“å</span>è®¸æŒ¯è½©</p></div><p>é©¬æ¥è¥¿äºš Â· 18 å² Â· å­¦ç”Ÿ</p><div className="identityStatus"><i/> ä¸æ–­å­¦ä¹ ä¸Žæˆé•¿</div></div></section>

  <section className="darrenAchievements section" id="achievements"><div className="achievementIntro"><p className="kicker">01 Â· æˆå°±</p><h2>æ­Œå”±æ¯”èµ›<br/>æˆå°±</h2><p>è®°å½•æˆ‘åœ¨èˆžå°ä¸Šçš„æ¯”èµ›ç»åŽ†ã€è¡¨æ¼”ä¸Žæˆç»©ã€‚</p><a className="button primary achievementArchiveButton" href="/zh/achievements">æŸ¥çœ‹æ‰€æœ‰æˆå°± â†’</a></div><article className="featuredAchievement"><div className="achievementYear">2025</div><div className="achievementCopy"><p className="achievementType">å›½é™…ä¸­æ–‡æ­Œæ›²å¤§èµ›</p><h3>2025å¹´æ–‡åŒ–ä¸­å›½Â·æ°´ç«‹æ–¹æ¯ä¸­æ–‡æ­Œæ›²å¤§èµ›</h3><p>å‚åŠ 2025å¹´æ–‡åŒ–ä¸­å›½Â·æ°´ç«‹æ–¹æ¯ä¸­æ–‡æ­Œæ›²å¤§èµ›ï¼Œè£èŽ·<strong>å…¨çƒç¬¬19å</strong>åŠ<strong>é“œå¥–</strong>ã€‚</p><div className="achievementResults"><span><small>å…¨çƒæŽ’å</small><b>ç¬¬19å</b></span><span><small>å¥–é¡¹</small><b>é“œå¥–</b></span></div></div><div className="achievementGallery"><figure className="achievementWide"><img src="/water-cube-2025-stage.jpeg" alt="Darren Khaw å‚ä¸Ž2025å¹´æ–‡åŒ–ä¸­å›½Â·æ°´ç«‹æ–¹æ¯ä¸­æ–‡æ­Œæ›²å¤§èµ›"/></figure><figure><img src="/water-cube-2025-trophy.jpeg" alt="2025å¹´æ–‡åŒ–ä¸­å›½Â·æ°´ç«‹æ–¹æ¯ä¸­æ–‡æ­Œæ›²å¤§èµ›é“œå¥–å¥–æ¯"/></figure><figure><img src="/water-cube-2025-winner.jpeg" alt="Darren Khaw æ‰‹æŒé“œå¥–å¥–æ¯"/></figure></div></article></section>

  <section className="darrenAbout section" id="about-darren"><div><p className="kicker">02 Â· å…³äºŽæˆ‘</p><h2>ä»ŽéŸ³ä¹ä¸­å­¦ä¹ ã€‚<br/>åœ¨è¡¨æ¼”ä¸­æˆé•¿ã€‚</h2></div><div><p className="darrenLead">å”±æ­Œæ˜¯æˆ‘ç”Ÿæ´»ä¸­é‡è¦çš„ä¸€éƒ¨åˆ†ã€‚æˆ‘å‚åŠ æ¯”èµ›æ¥æŒ‘æˆ˜è‡ªå·±ã€ç´¯ç§¯èˆžå°ç»éªŒï¼Œå¹¶æŒç»­æå‡è‡ªå·±ã€‚è¿™ä¸ªä½œå“é›†è®°å½•äº†æˆ‘çš„æˆé•¿è¿‡ç¨‹ä¸Žæ²¿é€”çš„æ¯ä¸ªé‡Œç¨‹ç¢‘ã€‚</p></div></section>

  <section className="darrenRoles section" id="roles"><div className="sectionIntro"><p className="kicker">03 Â· åˆ›æ„é¡¹ç›®</p><h2>èˆžå°ä¹‹å¤–ã€‚</h2></div><div className="roleGrid"><article><span>åˆ›æ„å“ç‰Œ</span><h3>DrunKitten</h3><p>æ±‡é›†æˆ‘æ‰€æœ‰åˆ›ä½œçš„ä¸»å“ç‰Œä¸Žåˆ›æ„ç©ºé—´ã€‚</p></article><article><span>çº¿ä¸ŠæœåŠ¡</span><h3>S&amp;E LAB</h3><p>æˆ‘æä¾›äººå£°ç§»é™¤ä¸ŽéŸ³é¢‘åˆ†ç¦»çš„çŽ°æœ‰æœåŠ¡ã€‚</p></article><article><span>å‘å±•ä¸­çš„éŸ³ä¹é¡¹ç›®</span><h3>DrunKitten Production</h3><p>éšç€æˆ‘ç»§ç»­å­¦ä¹ éŸ³ä¹åˆ¶ä½œï¼Œä¸ºæœªæ¥åŽŸåˆ›éŸ³ä¹å»ºç«‹çš„ç©ºé—´ã€‚</p></article></div></section>

  <section className="darrenCredits section"><DarrenLogo/><div><p className="kicker">04 Â· æœªæ¥ç½²åæ–¹å¼</p><div className="darrenCreditRows"><p><span>æ¼”å”±</span><strong>Darren Khaw</strong></p><p><span>åˆ¶ä½œ</span><strong>DrunKitten Production &amp; Darren Khaw</strong></p></div></div></section>

  <section className="darrenContact section" id="contact"><div className="contactIntro"><p className="kicker">05 Â· è”ç³»æ–¹å¼</p><h2>ä¸Žæˆ‘è”ç³»</h2><p>æ‚¨å¯ä»¥ç›´æŽ¥è”ç³»æˆ‘ï¼Œæˆ–é€šè¿‡ç¤¾äº¤åª’ä½“ä¸Žæˆ‘äº¤æµã€‚</p></div><div className="contactGrid"><a href="mailto:darrenkhaw@drunkitten.com"><span>ç”µå­é‚®ä»¶</span><strong>darrenkhaw@drunkitten.com</strong><i>â†—</i></a><a href="https://wa.me/601111909196" target="_blank" rel="noreferrer"><span>WhatsApp</span><strong>å‘é€ä¿¡æ¯</strong><i>â†—</i></a><a href="https://www.instagram.com/darrenkhaw0920/" target="_blank" rel="noreferrer"><span>Instagram</span><strong>@darrenkhaw0920</strong><i>â†—</i></a><a href="https://www.facebook.com/darren.khaw.2025" target="_blank" rel="noreferrer"><span>Facebook</span><strong>Darren Khaw</strong><i>â†—</i></a></div></section>

  <footer className="darrenFooter standaloneFooter"><a href="#top"><DarrenLogo/></a><nav className="darrenSiteLinks" aria-label="DrunKitten ç½‘ç«™ç½‘ç»œ"><a href="https://drunkitten.com/zh">DrunKitten</a><a href="https://drunkitten.com/zh/se-lab">S&amp;E LAB</a><a href="https://drunkitten.com/zh/production">éŸ³ä¹åˆ¶ä½œ</a></nav><a href="#top">è¿”å›žé¡¶éƒ¨ â†‘</a><small>Â© {new Date().getFullYear()} Darren Khaw Â· å­¦ç”Ÿ</small></footer>
</main>}
