CREATE TABLE IF NOT EXISTS antigravity_state (
    storage_key VARCHAR(191) NOT NULL PRIMARY KEY,
    storage_value LONGTEXT NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;